# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Studio < Formula
  desc "Design tokens management CLI for Tokens Studio"
  homepage "https://tokens.studio"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tokens-studio/studio-cli-releases/releases/download/v0.1.1/studio_0.1.1_darwin_amd64.tar.gz"
      sha256 "355d3f00abcf449a5bc8561642abab41fd5a8ab17e912d12f1a59d3b24503a74"

      define_method(:install) do
        bin.install "studio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tokens-studio/studio-cli-releases/releases/download/v0.1.1/studio_0.1.1_darwin_arm64.tar.gz"
      sha256 "633b66b73cca35c72c83e558d34cc66abd05ed844bb0340fa7cfc6db111269d3"

      define_method(:install) do
        bin.install "studio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokens-studio/studio-cli-releases/releases/download/v0.1.1/studio_0.1.1_linux_amd64.tar.gz"
      sha256 "337688970c01f83dc95bded79edc877e42f4cf43ffb10829960c215ed6fef931"
      define_method(:install) do
        bin.install "studio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokens-studio/studio-cli-releases/releases/download/v0.1.1/studio_0.1.1_linux_arm64.tar.gz"
      sha256 "5ac6825a51bd2726e12930394a906cb4f6750f11e47836b1f8f8ced0bdc41dfe"
      define_method(:install) do
        bin.install "studio"
      end
    end
  end

  test do
    system "#{bin}/studio", "--version"
  end
end
