# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Studio < Formula
  desc "Design tokens management CLI for Tokens Studio"
  homepage "https://tokens.studio"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tokens-studio/studio-cli-releases/releases/download/v0.1.0/studio_0.1.0_darwin_amd64.tar.gz"
      sha256 "6ff3ff264788cb2d1aa6390ff70f5e3cd98d5fecd0eff5297e134e056d6dbe13"

      define_method(:install) do
        bin.install "studio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tokens-studio/studio-cli-releases/releases/download/v0.1.0/studio_0.1.0_darwin_arm64.tar.gz"
      sha256 "1719fe808f8a3eeaa6e5b1019d76bbc9b5da292106a317b3ced834895e588418"

      define_method(:install) do
        bin.install "studio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokens-studio/studio-cli-releases/releases/download/v0.1.0/studio_0.1.0_linux_amd64.tar.gz"
      sha256 "8112328b774be0ef88d660a3e5f2e65bdc1f633ae047f166c298b59a23617ce5"
      define_method(:install) do
        bin.install "studio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokens-studio/studio-cli-releases/releases/download/v0.1.0/studio_0.1.0_linux_arm64.tar.gz"
      sha256 "a2cf262ae8ee6edb14115b077932e8b2f95fe4cb7f41364ad64bff5bca440ab6"
      define_method(:install) do
        bin.install "studio"
      end
    end
  end

  test do
    system "#{bin}/studio", "--version"
  end
end
