# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Studio < Formula
  desc "Design tokens management CLI for Tokens Studio"
  homepage "https://tokens.studio"
  version "0.2.4"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tokens-studio/studio-cli-releases/releases/download/v0.2.4/studio_0.2.4_darwin_amd64.tar.gz"
      sha256 "1f839c567022c9c3a817d954c535a28329af94127af0f71a7d75bab9300e33b0"

      define_method(:install) do
        bin.install "studio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tokens-studio/studio-cli-releases/releases/download/v0.2.4/studio_0.2.4_darwin_arm64.tar.gz"
      sha256 "d2f08b631311902cd1ee7505795b87400361d3e3b0815bacc62a8650c917dffc"

      define_method(:install) do
        bin.install "studio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokens-studio/studio-cli-releases/releases/download/v0.2.4/studio_0.2.4_linux_amd64.tar.gz"
      sha256 "af449005f05614dc312fe4f0f15289e5663e35bedb1cc27e21e5e36162a299a3"
      define_method(:install) do
        bin.install "studio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tokens-studio/studio-cli-releases/releases/download/v0.2.4/studio_0.2.4_linux_arm64.tar.gz"
      sha256 "a835e675649faac4a5f9729c5b1b3cf5ac9f00d9522762a078012c255c1d6573"
      define_method(:install) do
        bin.install "studio"
      end
    end
  end

  test do
    system "#{bin}/studio", "--version"
  end
end
